
DROP TABLE IF EXISTS "MERCHANT";
CREATE TABLE "MERCHANT" (
   "UUID" UUID NOT NULL UNIQUE,
   "NAME"  VARCHAR(255) NOT NULL,
   PRIMARY KEY("UUID")
);

DROP TABLE IF EXISTS "USER";
CREATE TABLE "USER" (
   "UUID" UUID NOT NULL UNIQUE,
   "MERCHANT_ID" UUID NOT NULL,
   "NAME"  VARCHAR(255) NOT NULL,
   CONSTRAINT fk_user_MERCHANT FOREIGN KEY ("MERCHANT_ID") REFERENCES "MERCHANT"("UUID"),
   PRIMARY KEY("UUID")
);

DROP TABLE IF EXISTS "CATEGORY";
CREATE TABLE "CATEGORY" (
   "UUID" UUID NOT NULL UNIQUE PRIMARY KEY,
   "NAME"  VARCHAR(255) NOT NULL,
   PRIMARY KEY("UUID")
);

DROP TABLE IF EXISTS "PRODUCT";
CREATE TABLE "PRODUCT" (
   "UUID" UUID  NOT NULL UNIQUE PRIMARY KEY,
   "MERCHANT_ID" UUID  NOT NULL,
   "CATEGORY_ID" UUID  NOT NULL,
   "NAME"  VARCHAR(255) NOT NULL,
   CONSTRAINT fk_product_MERCHANT FOREIGN KEY ("MERCHANT_ID") REFERENCES "MERCHANT"("UUID"),
   CONSTRAINT fk_product_CATEGORY FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("UUID"),
   PRIMARY KEY("UUID")
);